# Generated by Django 5.1.6 on 2025-02-25 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_user_post_auther_alter_post_date_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(default='none'),
            preserve_default=False,
        ),
    ]
